title: Toolog
description: 개발자를 위한 실전 웹툴 제작·활용 아카이브
url: "https://toolog.sooyadev.com"
baseurl: ""
lang: ko-KR
timezone: Asia/Seoul

# 테마
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 작성/출력 설정
markdown: kramdown
kramdown:
  input: GFM

permalink: /:categories/:title/
future: false
show_drafts: false

# Minima
minima:
  skin: auto
  social_links: []

header_pages:
  - about.md

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "toolog"
